### ISSUE TITLE
Uncaught TypeError: 'QVariant' object is not subscriptable


### ISSUE THREAD

**Issue by UrbanPlan-LDB** [stangandaho/Extractor#2]
Impossibile caricare il plugin 'extractor' a causa di un errore chiamando il metodo classFactory()
Steps to reproduce
 1. First 
 2. Second 
 3. Third 

```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\extractor\__init__.py", line 36, in classFactory
    return Extractor(iface)
  File "C:\Users/Lucio De Benedictis/AppData/Roaming/QGIS/QGIS3\profiles\Lucio_02_23/python/plugins\extractor\Extractor.py", line 51, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

```
extractor 0.21, QGIS 3.28.4-Firenze on Windows 10

**Comment by stangandaho** [comment]
Is the plugin successfully installed?

**Comment by UrbanPlan-LDB** [comment]
Puglin apparently installs but is automatically disabled because it cannot be started.

**Comment by stangandaho** [comment]
Please go to the raster menu to see if you can't find 'Extractor'. If it is found, click on it to see if the interface does not appear.

**Comment by UrbanPlan-LDB** [comment]
not appear in the "raster" menu.

**Comment by stangandaho** [comment]
I'm having trouble following the problem. I tried to install the plugin on other computers and I had no difficulty. Can you also try on another machine on your side?
