### ISSUE TITLE
Uncaught Type Error when trying to extract data

### ISSUE THREAD

**Issue by Luca023** [stangandaho/Extractor#4]
I'm getting TypeErrors on different plattforms (macOS ventura 13.4.1 + QGIS v. 3.32.1 + Extractor v. 1.1 and Microsoft Windows 11 + QGIS 3.32.1 + Extractor v. 1.1) when I try to extract raster data using points. Originally I wanted to extract the data from an .asc-File which I have converted to geoTIFF. After the TypeError persisted on the two different platforms, I tried using the thenbytenraster from the test folder and created another custom point-shapefile. This still didn't resolve the issue. During every attempt, I have selected the same CRS for the raster and the shapefile. 

Another issue under macOS is that I had to paste the paths to the files manually, as the path-selector interface hasn't been working.

Many thanks in advance!

WARNING    Traceback (most recent call last):
              File "/.../plugins/extractor/Extractor_dialog.py", line 194, in display_raster_data
              with_point = self.raster_point_df()
              File "/.../plugins/extractor/Extractor_dialog.py", line 319, in raster_point_df
              raster_array = raster_band.ReadAsArray(px, py, 1, 1)[0,0]
             TypeError: 'NoneType' object is not subscriptable

**Comment by stangandaho** [comment]
Hello,
I'm very sorry replying lately.
Did you tried to display both raster and shapefile clicking on Show button
to be sure the data are overlapped? Basically Extractor try to conform CRS
but I recommend to switch the CRS of shapefile to CRS of raster.
