### ISSUE TITLE
An error has occurred while executing Python code

### ISSUE THREAD

**Issue by benoit-demars73** [stangandaho/Extractor#7]
I am using QGIS LTR 3.34.12 and downloaded Extractor 1.2 - The window opens nicely and I can select the files needed and statistics i want, but run generate an error message and no result. I am trying to extract statistics from a geotiff raster by a shapefile multilinestring (one stream network) with a few features, including SEGMENT_ID (a small section of the stream network) which I want to use for zonal statistics. Both files are in the same CRS and show correctly, the attribute table also display correctly in QGIS. I have QGIS linked to Python 3.12.7 in C:\OSGeo4W\apps\Python312. 

I get the following error message: 
2024-11-07T12:25:56     WARNING    Traceback (most recent call last):
              File "C:\Users/BDE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\extractor\Extractor_dialog.py", line 189, in display_raster_data
              raster_line_stats = self.raster_line_stats()
              ^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/BDE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\extractor\Extractor_dialog.py", line 573, in raster_line_stats
              df = groupby_agg(df = result_df, group_cols = self.field_chosen(),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/BDE/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\extractor\src\Zonal_stats.py", line 87, in groupby_agg
              result_df = df.groupby(group_cols)[value_col].agg(agg_funcs)
              ^^^^^^^^^^^^^^^^^^^^^^
              File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\core\frame.py", line 9183, in groupby
              return DataFrameGroupBy(
              ^^^^^^^^^^^^^^^^^
              File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\core\groupby\groupby.py", line 1329, in __init__
              grouper, exclusions, obj = get_grouper(
              ^^^^^^^^^^^^
              File "C:\OSGeo4W\apps\Python312\Lib\site-packages\pandas\core\groupby\grouper.py", line 1043, in get_grouper
              raise KeyError(gpr)
             KeyError: 'SEGMENT_ID'
            
Did I miss something ?
Thank you, Benoit

**Comment by stangandaho** [comment]
Hello @benoit-demars73 
Thanks for the feedback

The error message you're encountering suggests that Extractor is having trouble locating the `SEGMENT_ID` field in the shapefile's attribute table. The `KeyError: 'SEGMENT_ID` typically occurs when `SEGMENT_ID` column does not exist or is not accessible in the data frame. If `SEGMENT_ID` has a different name or includes characters like spaces, this might cause issues.
If the name is different, update the selection in the Extractor plugin to match the exact field name.

- Can you confirm that `SEGMENT_ID` exist and content is not empty?
- Can you try (create) other column name that could represent the line ID?

You could share with me the shapefile for deep checking.

**Comment by benoit-demars73** [comment]
Dear Stanislas, 
I appreciate your feedback. The shapefile do have SEGMENT_ID with content for all rows. The shapefile also worked with other plugins such as Stream Feature Extractot, the Road Slope Calculator, and the QGIS aggregate function by SEGMENT_ID.
Maybe the files are too big: the geotif file is 728 MB and the shapefile about 11 MB.
You may find the files here: https://drive.google.com/drive/folders/1PzbHZFT0us6EwPvGqExkxZTUhhRXGcJA 
Cheers, Benoît
